name: ArriveHive
favicon: null
layout_spectrum: 0.6258908945601434
typography_spectrum: 0.8262042668648064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.601322022266686
  lightness: 0.997322459006682
  saturation: 0.7450224093627185
  rhythmicContrast: 0.8114591760095209
purpose: []
